version: '2'
services:
    python:
        build:
            context: .
            dockerfile: ./services/python/Dockerfile
        command: ["python", "-m", "flask", "run"]
        ports:
            - 5000:5000
        volumes:
            - .:/app
